[features]
seeds = false
skip-lint = false
[programs.localnet]
solquad = "CzyDhoJqZHfheuFbhu4sW5fXLYYyBAnf6Wrnwy7A4ghd"

[programs.devnet]
solquad = "CzyDhoJqZHfheuFbhu4sW5fXLYYyBAnf6Wrnwy7A4ghd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/suvineetkalsi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
