[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_solana_nft = "EKcavhoQbsx3GCZuEyA5mbLsCMpVmniNvMqg6KEkcNoQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/suvineetkalsi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
