[features]
seeds = false
skip-lint = false
[programs.localnet]
todo_list_app = "BbRjfZLZiQtRLK8cfWYf8QEn1Mz6suspyJfxikw5xQmm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/suvineetkalsi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
