[features]
seeds = false
skip-lint = false
[programs.localnet]
waffle_maker = "r7t8X1SDve8TRZQwLfJAaDpd5wDvtKuLUejkucAVkvv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/suvineetkalsi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
