[features]
seeds = false
skip-lint = false
[programs.localnet]
lend_borrow = "bpuPFSHXB4e8CAy1akbNH64XmBdBfzFH977x18Jng6f"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/suvineetkalsi/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
